language: java
jdk:
  - oraclejdk7

notifications:
  email:
    - fkorotkov@twitter.com
    - tdesai@twitter.com

install: ./scripts/download-ci-environment.sh

env:
  global:
    - OSS_PANTS_HOME=./.cache/intellij/pants
  matrix:
    - IJ_VERSION="14" IJ_BUILD_NUMBER="139.223" USE_PANTS_TO_COMPILE="true"
    - IJ_VERSION="14" IJ_BUILD_NUMBER="139.223" USE_PANTS_TO_COMPILE="false"
    - IJ_VERSION="14.0.3" IJ_BUILD_NUMBER="139.1117" IJ_ULTIMATE=true
    - IJ_VERSION="14.0.3" IJ_BUILD_NUMBER="139.1117"

script:
  - ./scripts/run-tests-ci.sh --test-junit-jvm-options="-Dpants.compiler.enabled=${USE_PANTS_TO_COMPILE:-true}"
  - ./scripts/run-custom-integration.sh
      -r $OSS_PANTS_HOME
      -t examples/src/scala/com/pants/example/hello,examples/src/java/com/pants/examples/hello
