language: java
jdk:
- oraclejdk7
notifications:
  email:
    - fkorotkov@twitter.com
    - tdesai@twitter.com
install: ./scripts/setup-ci-environment.sh

script: ./scripts/run-tests-ci.sh
        ./scripts/run-custom-integration.sh -l
        -r ../pants
        -t examples/src/scala/com/pants/example/hello,examples/src/java/com/pants/examples/hello